### ISSUE TITLE
Errors on a few sequences

### ISSUE THREAD

**Issue by harrismia** [jodyphelan/TBProfiler#6] opened 2017-07-31 17:01 UTC
Hi Jody, 

      I am getting errors for the following sequences:   SRR5153232, SRR5153810, SRR5153908

      Any idea why TBprofiler is not able to compute a prediction for these sequences?  Below is the output that I am getting from TBprofiler.   Thanks!

          Michael 

_Checking input files
Performing mapping
set -euf pipefail; /sysapps/cluster/software/TBProfiler/0.2.1/bin/snap-aligner paired /sysapps/cluster/software/TBProfiler/0.2.1/ref -compressedFastq ../../SRR5153232_1.fastq.gz ../../SRR51532
32_2.fastq.gz -t 4 -o -bam - | /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools sort -o SRR5153232.bam -@ 4 - && /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools index SRR5153232
.bam
Calling Variants
set -euf pipefail; /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools view -bL /sysapps/cluster/software/TBProfiler/0.2.1/db/drdb.bed SRR5153232.bam | /sysapps/cluster/software/TBProfiler
/0.2.1/bin/lofreq indelqual -u 30 - |/sysapps/cluster/software/TBProfiler/0.2.1/bin/lofreq call -f /sysapps/cluster/software/TBProfiler/0.2.1/ref/MTB-h37rv_asm19595v2-eg18.fa --call-indels - |
 /sysapps/cluster/software/TBProfiler/0.2.1/bin/bcftools norm -f /sysapps/cluster/software/TBProfiler/0.2.1/ref/MTB-h37rv_asm19595v2-eg18.fa - > SRR5153232.dr.vcf
Loading annotation
Don't know what to do! ERROR!!
Finished tb-profiler for SRR5153232.

---------------------------------------------
Checking input files
Performing mapping
set -euf pipefail; /sysapps/cluster/software/TBProfiler/0.2.1/bin/snap-aligner paired /sysapps/cluster/software/TBProfiler/0.2.1/ref -compressedFastq ../../SRR5153810_1.fastq.gz ../../SRR51538
10_2.fastq.gz -t 4 -o -bam - | /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools sort -o SRR5153810.bam -@ 4 - && /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools index SRR5153810
.bam
Calling Variants
set -euf pipefail; /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools view -bL /sysapps/cluster/software/TBProfiler/0.2.1/db/drdb.bed SRR5153810.bam | /sysapps/cluster/software/TBProfiler
/0.2.1/bin/lofreq indelqual -u 30 - |/sysapps/cluster/software/TBProfiler/0.2.1/bin/lofreq call -f /sysapps/cluster/software/TBProfiler/0.2.1/ref/MTB-h37rv_asm19595v2-eg18.fa --call-indels - |
 /sysapps/cluster/software/TBProfiler/0.2.1/bin/bcftools norm -f /sysapps/cluster/software/TBProfiler/0.2.1/ref/MTB-h37rv_asm19595v2-eg18.fa - > SRR5153810.dr.vcf
Loading annotation
Don't know what to do! ERROR!!
Finished tb-profiler for SRR5153810

----------------------------------------------------
Checking input files
Performing mapping
set -euf pipefail; /sysapps/cluster/software/TBProfiler/0.2.1/bin/snap-aligner paired /sysapps/cluster/software/TBProfiler/0.2.1/ref -compressedFastq ../../SRR5153908_1.fastq.gz ../../SRR51539
08_2.fastq.gz -t 4 -o -bam - | /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools sort -o SRR5153908.bam -@ 4 - && /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools index SRR5153908
.bam
Calling Variants
set -euf pipefail; /sysapps/cluster/software/TBProfiler/0.2.1/bin/samtools view -bL /sysapps/cluster/software/TBProfiler/0.2.1/db/drdb.bed SRR5153908.bam | /sysapps/cluster/software/TBProfiler
/0.2.1/bin/lofreq indelqual -u 30 - |/sysapps/cluster/software/TBProfiler/0.2.1/bin/lofreq call -f /sysapps/cluster/software/TBProfiler/0.2.1/ref/MTB-h37rv_asm19595v2-eg18.fa --call-indels - |
 /sysapps/cluster/software/TBProfiler/0.2.1/bin/bcftools norm -f /sysapps/cluster/software/TBProfiler/0.2.1/ref/MTB-h37rv_asm19595v2-eg18.fa - > SRR5153908.dr.vcf
Loading annotation
Don't know what to do! ERROR!!
Finished tb-profiler for SRR5153908._

**Comment by jodyphelan** [comment] 2017-07-31 19:30
Hi Michael,

I have looked at the files and believe I know what the problem is. The issue relates to when a large deletion causes low quality mapping around it's breakpoints. I will release a fix for this asap.

Jody

**Comment by harrismia** [comment] 2017-07-31 20:03
Hi Jody, 

           Interesting.. Thanks for your quick response!  Best,

**Comment by jodyphelan** [comment] 2017-08-02 17:44
Hi Michael,

I have updated the TBProfiler. It now looks for large deletions first and does not look for small variants in genes where it finds partial deletions. One assumption this makes is that partial gene deletions are of higher importance when it comes to conferring drug resistance, which is supported by our data.

Jody

**Comment by harrismia** [comment] 2017-08-02 17:54
Thanks very much Jody! I will give it a try and let you know if I find any issues.    Best, 

  Michael

**Closed** 2017-08-03 18:05 UTC
